
# Archivo: docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: erp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - erp-network

  springboot-app:
    build: .
    container_name: erp-springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:adminpass@mongodb:27017/sw2-Erp?authSource=admin
    depends_on:
      - mongodb
    networks:
      - erp-network

volumes:
  mongodb_data:

networks:
  erp-network: